export function SummaryPanel({ summary, onClose }) {
  if (!summary) return null;

  return (
    <div className="absolute inset-0 bg-black/80 flex items-center justify-center z-50 p-6">
      <div className="bg-[#0d0d1a] border border-purple-500/40 rounded-lg max-w-xl w-full max-h-[80vh] flex flex-col shadow-2xl shadow-purple-900/30">
        <div className="flex items-center justify-between px-5 py-3 border-b border-white/10">
          <span className="font-pixel text-[11px] text-purple-400">{'★'} DEBATE COMPLETE — FINAL ROADMAP</span>
          <button
            onClick={onClose}
            className="text-white/40 hover:text-white/80 font-pixel text-[10px] transition-colors"
          >
            {'✕'} CLOSE
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5">
          <p className="font-pixel text-[10px] text-white/80 leading-relaxed whitespace-pre-wrap">
            {summary}
          </p>
        </div>
        <div className="px-5 py-3 border-t border-white/10">
          <p className="text-[8px] font-pixel text-white/30">
            Generated by AI Startup Boardroom — {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}
